---
- hosts: grp1
  user: root
  become: yes
  connection: ssh
  tasks:
  - name: install nginx
    apt:
      pkg: nginx
      state: present
  - name: nginx status
    service:
      name: nginx
      state: stopped      


